version: '2.4'

services:
  router:
    image: ayudadigital/gp-haproxy:2.0.0
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/router/usr/local/etc/haproxy:/usr/local/etc/haproxy
      - ./data/router/etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: ${DATASOURCE_DBNAME}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    volumes:
      - ./data/db/var/lib/postgresql/data:/var/lib/postgresql/data
    restart: unless-stopped
  app:
    image: ayudadigital/huelladigital-backend:${tag_app}
    environment:
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_DBNAME: ${DATASOURCE_DBNAME}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      PROFILE: ${PROFILE}
      BASE_URI: ${BASE_URI}
    ports:
      - 8080:8080
    restart: unless-stopped
