name: Healthcheck

on:
  pull_request:
    branches: [ develop ]
  schedule:
    - cron:  '* * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Get previous state
        id: cache-state
        uses: actions/cache@v2
        with:
          path: health/status
          key: ${{ runner.os }}-test
      - name: Healthcheck (dev)
        id: healthcheck
        env:
          HEALTH_URL_DEV: ${{ secrets.HEALTH_URL_DEV }}
        run: |
          ls -l
          mkdir -p health/status
          test -f health/status/dev || echo "UNKNOWN" > health/status/dev
          echo "::set-output name=previous::$(cat health/status/dev)\n"
          curl -L -w "%{http_code}" -o /dev/null -s ${HEALTH_URL_DEV} > health/status/dev
          echo "::set-output name=current::$(cat health/status/dev)\n"
      - name: Compare status
        run: |
          #mkdir -p health/status
          #test -f health/status/dev || echo "Unknown" > health/status/dev
          #current=$(cat current)
          current=${{ steps.healthchek.outputs.current }}
          previous=${{ steps.healthchek.outputs.previous }}
          echo "Previous status: $previous"
          echo "Latest status: $current"
          if [ "$current" != "$previous" ]; then
            echo "Send alert."
          fi
