name: Healthcheck

on:
  pull_request:
    branches: [ develop ]
  schedule:
    - cron:  '* * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Get previous state
        id: cache-state
        uses: actions/cache@v2
        with:
          path: health/status
          key: ${{ runner.os }}-test
      - name: Healthcheck (dev)
        id: healthcheck
        env:
          HEALTH_URL_DEV: ${{ secrets.HEALTH_URL_DEV }}
        run: |
          #ls -l health/status || true
          #cat health/status/dev || true
          mkdir -p health/status
          test -f health/status/dev || echo "UNKNOWN" > health/status/dev
          echo "::set-output name=previous::$(cat health/status/dev)"
          curl -L -w "%{http_code}" -o /dev/null -s ${HEALTH_URL_DEV} > health/status/dev
          echo "::set-output name=current::$(cat health/status/dev)"
      - name: Compare status
        env:
          PREVIOUS: ${{ steps.healthcheck.outputs.previous }}
          CURRENT: ${{ steps.healthcheck.outputs.current }}
        run: |
          #mkdir -p health/status
          #test -f health/status/dev || echo "Unknown" > health/status/dev
          #current=$(cat current)
          echo "Previous status: $PREVIOUS"
          echo "Latest status: $CURRENT"
          if [ "$CURRENT" != "$PREVIOUS" ]; then
            echo "Send alert."
          fi
