name: Healthcheck

on:
  pull_request:
    branches: [ develop ]
  schedule:
    - cron:  '* * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Healthcheck (dev)
        env:
          HEALTH_URL_DEV: ${{ secrets.HEALTH_URL_DEV }}
        run: |
          echo "Run ID: ${GITHUB_RUN_ID}"
          echo "Run Nb: ${GITHUB_RUN_NUMBER}"
          curl -IL -w "%{http_code}" -o /dev/null -s ${HEALTH_URL_DEV} > latest
      - name: Get previous state
        uses: actions/download-artifact@v2
        continue-on-error: true
        with:
          name: dev
          path: health/status
      - name: Compare status
        if: always()
        run: |
          mkdir -p health/status
          test -f health/status/dev || echo "Unknown" > health/status/dev
          echo "Previous status: $(cat health/status/dev)"
          echo "Latest status: $(cat latest)"

