name: Healthcheck

on:
  pull_request:
    branches: [ develop ]
  schedule:
    - cron:  '* * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Get previous state
        id: cache-state
        uses: actions/cache@v2
        with:
          path: health/status
          key: ${{ runner.os }}-healthcheck-dev
      - name: Healthcheck (dev)
        id: healthcheck
        env:
          HEALTH_URL_DEV: ${{ secrets.HEALTH_URL_DEV }}
        run: |
          mkdir -p health/status
          test -f health/status/dev || echo "UNKNOWN" > health/status/dev
          echo "::set-output name=previous::$(cat health/status/dev)"
          HTTP_STATUS=$(curl -L -w "%{http_code}" -o /dev/null -s ${HEALTH_URL_DEV})
          [[ $HTTP_STATUS = 200 ]] && CURRENT="UP" || CURRENT="DOWN"
          echo $CURRENT > health/status/dev
          echo "::set-output name=current::$(cat health/status/dev)"
      - name: Compare status
        env:
          PREVIOUS: ${{ steps.healthcheck.outputs.previous }}
          CURRENT: ${{ steps.healthcheck.outputs.current }}
        run: |
          echo "Previous status: $PREVIOUS"
          echo "Latest status: $CURRENT"
          if [ "$CURRENT" != "$PREVIOUS" ]; then
            echo "Send alert."
            echo "::set-output name=notify::$CURRENT"
          fi
      - name: Notify
        if: steps.foo.outputs.notify
        env:
          CURRENT: ${{ steps.healthcheck.outputs.current }}
        run: |
          echo "Notify: $CURRENT"
